In [8]:
import pandas as pd
import numpy as np
import json
import ast
import black
import os
import time

%load_ext jupyter_black

The jupyter_black extension is already loaded. To reload it, use:
  %reload_ext jupyter_black

In [9]:
a = [1, 2, 3]
a.reverse()
a

[3, 2, 1]

In [10]:
# raw_data = pd.read_csv("raw_data_2023-06-16_18:39:47.csv", index_col=0)
# raw_data = pd.read_csv("raw_data_2023-06-25_22:31:05.csv", index_col=0)

In [11]:
def read_all_csv_from_path(path: str) -> pd.DataFrame:
    """_summary_

    Args:
        path (str): _description_

    Returns:
        pd.DataFrame: _description_
    """
    df = pd.concat(
        [
            pd.read_csv(f"{path}/{file}")
            for file in os.listdir(path)
            if file.endswith(".csv")
        ],
        ignore_index=True,
    )
    return df

In [13]:
path = os.getcwd()
raw_data = read_all_csv_from_path(path)
unique_raw_data = raw_data.convert_dtypes().drop_duplicates(subset=["seller_name"])

In [16]:
all_seller_product = raw_data.convert_dtypes().drop_duplicates(subset=["seller_name"])

In [ ]:
# all_seller_product

In [17]:
len(all_seller_product)

136

In [18]:
all_seller_product = raw_data["raw_data"].values
# ast.literal_eval(all_seller_product[1])["product_3"]

In [19]:
def normalize_shipping_price(raw_shipping_price):
    try:
        return float(
            raw_shipping_price.replace(",", ".")
            .replace("€", "")
            .replace("Gratuit", "0")
        )
    except Exception as e:
        return 0

all_seller_product

In [22]:
info_all_seller_product = []
product_check = set()
product_without_concurrent = []

for all_product_seller in all_seller_product:
    dict_all_product_seller = ast.literal_eval(all_product_seller)
    for product in dict_all_product_seller.values():
        if product["ean"] != "":
            try:
                info_product = {}
                ean = product["ean"]
                price = product["seller_price"]
                name_seller = product["seller_name_fp"]
                if ean in product_check:
                    continue
                # print(name_seller)
                try:
                    others_offer = product["offers"]
                    pass
                except Exception:
                    product_without_concurrent.append(product)
                    # print(product["title"])
                    # print(product["seller_price"])
                    # print("ici", name_seller)
                    # print(ean)
                    # print("----------------------------")
                    continue
                if name_seller == "":
                    price_site_seller = price
                    all_price_other_seller = {}
                    for info_other_product in others_offer:
                        if (
                            info_other_product["seller_name"].lower().replace(" ", "")
                            == "cdiscount"
                        ):
                            continue
                        else:
                            all_price_other_seller[
                                info_other_product["seller_name"]
                            ] = {
                                "price": float(
                                    info_other_product["seller_price"]
                                    .replace("\n", ".")
                                    .replace("€", "")
                                ),
                                "shipping_rate_price": normalize_shipping_price(
                                    info_other_product["shipping_rate_price"]
                                ),
                            }
                    info_product["ean"] = ean
                    info_product["list_other_price"] = all_price_other_seller
                    product_check.add(ean)
                    continue
                else:
                    all_price_other_seller = {}
                    for info_other_product in others_offer:
                        if (
                            info_other_product["seller_name"].lower().replace(" ", "")
                            == "cdiscount"
                        ):
                            price_site_seller = float(
                                info_other_product["seller_price"]
                                .replace("\n", ".")
                                .replace("€", "")
                            )
                            info_product["price_site_seller"] = price_site_seller
                        else:
                            all_price_other_seller[
                                info_other_product["seller_name"]
                            ] = {
                                "price": float(
                                    info_other_product["seller_price"]
                                    .replace("\n", ".")
                                    .replace("€", "")
                                ),
                                "shipping_rate_price": normalize_shipping_price(
                                    info_other_product["shipping_rate_price"]
                                ),
                            }
                    info_product["ean"] = ean
                    info_product["list_other_price"] = all_price_other_seller
                    product_check.add(ean)
                info_all_seller_product.append(info_product)
            except Exception:
                pass

In [23]:
len(info_all_seller_product)

1174

In [37]:
# info_all_seller_product

In [38]:
# info_all_seller_product[0]["list_other_price"]

In [39]:
# product_to_keep

In [30]:
absolute_threshold = 50
relative_threshold = 0.2
product_to_keep = []
commission = 0.22
min_margin = 20
decote = 0.2
magin_rate_to_apply = 0.33
for dict_product_info in info_all_seller_product:
    try:
        list_sorted_price_other_seller = [
            v
            for k, v in sorted(
                dict_product_info["list_other_price"].items(),
                key=lambda x: x[1]["price"] + x[1]["shipping_rate_price"],
            )
        ]
        margin = (
            list_sorted_price_other_seller[0]["price"]
            - list_sorted_price_other_seller[0]["shipping_rate_price"]
            - dict_product_info["price_site_seller"]
        ) - commission * list_sorted_price_other_seller[0]["price"]
        if margin >= min_margin:
            product_to_keep.append(
                {
                    "ean": dict_product_info["ean"],
                    "price_without_decode": list_sorted_price_other_seller[0]["price"]
                    * (1 + decote),
                    "price_with_decode": list_sorted_price_other_seller[0]["price"],
                    "margin": margin,
                    "shipping_rate_price": list_sorted_price_other_seller[0][
                        "shipping_rate_price"
                    ],
                }
            )
        elif margin <= 0 and dict_product_info["price_site_seller"]:
            product_to_keep.append(
                {
                    "ean": dict_product_info["ean"],
                    "price_without_decode": dict_product_info["price_site_seller"]
                    * (1 + magin_rate_to_apply)
                    * (1 + decote),
                    "price_with_decode": dict_product_info["price_site_seller"]
                    * (1 + magin_rate_to_apply),
                    "margin": (1 + magin_rate_to_apply)
                    * dict_product_info["price_site_seller"],
                    "shipping_rate_price": list_sorted_price_other_seller[0][
                        "shipping_rate_price"
                    ],
                }
            )
        continue
    except Exception as e:
        continue

In [31]:
len(product_to_keep)

450

absolute_threshold = 50
relative_threshold = 0.3
product_to_keep = dict()
for dict_product_info in info_all_seller_product:
    try:
        list_sorted_price_other_seller = [
            v
            for k, v in sorted(
                dict_product_info["list_other_price"].items(), key=lambda x: x[1]
            )
        ]
        diff_price = (
            list_sorted_price_other_seller[0] - dict_product_info["price_site_seller"]
        )
        relative_diff = (
            list_sorted_price_other_seller[0] - dict_product_info["price_site_seller"]
        ) / dict_product_info["price_site_seller"]
        if relative_diff > relative_threshold:
            if diff_price > absolute_threshold:
                product_to_keep[str(dict_product_info["ean"])] = (
                    dict_product_info["price_site_seller"] * 1.2
                )
        continue
    except Exception:
        continue

In [32]:
path = "S16 (2).xlsx"
df_template = pd.read_excel(path)

In [33]:
raw_data = pd.read_excel(path, header=None)
header_idx = raw_data[raw_data[0].eq("Votre référence / Your reference")].index.values[
    0
]

In [34]:
clean_data = pd.read_excel(io=path, header=3)

In [35]:
clean_data.columns

Index(['Votre référence / Your reference', 'EAN (Cdiscount)\nGTIN (Octopia)',
       'Sous état du produit / Product condition', 'Stock',
       'Prix (TTC) / Price (incl.tax)', 'TVA (%) / VAT (%)',
       'Eco Part (montant/amount)\n(France)', 'DEA (montant/amount)\n(France)',
       'Copie Privée (montant) / Private Copy (amount) \n(France)',
       'Chemical Tax \n(montant/amount) \n(Suède/Sweden)',
       'Conditionnement :\nQuantité totale vendue / Packaging, conditioning : \nTotal quantity sold',
       'Conditionnement :\nUnité de vente / Packaging, conditioning : \nSales unit',
       'Prix de référence (TTC) / Reference price (incl.tax)',
       'Commentaire offre /\nOffers comment',
       'Mécanique commerciale /\nPromotion type', 'Début / Start',
       'Unnamed: 16', 'Fin / End', 'Unnamed: 18', 'Remise (%) /\nDiscount (%)',
       'Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales',
       'S’aligner automatiquement sur la meilleure offre / Automatically set to best offer',
       'Plus bas prix autorisé (€)(TTC)(Prix plancher) / Lowest allowable price (€)(incl.tax) (floor price)',
       'Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days)',
       'Suivi / Tracked (Mandatory)', 'Unnamed: 25', 'Recommandé / Registered',
       'Unnamed: 27'],
      dtype='object')

In [36]:
list_df = []
for i, product in enumerate(product_to_keep):
    tmp_clean_data = pd.DataFrame(
        {
            "Votre référence / Your reference": "ms-" + product["ean"],
            "EAN (Cdiscount)\nGTIN (Octopia)": int(product["ean"]),
            "Stock": 10,
            "Prix de référence (TTC) / Reference price (incl.tax)": product[
                "price_without_decode"
            ],
            "Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales": product[
                "price_with_decode"
            ],
            "Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days)": 3,
            "Suivi / Tracked (Mandatory)": product["shipping_rate_price"],
            "ecommandé / Registered": product["shipping_rate_price"],
        },
        index=[i],
    )
    list_df.append(tmp_clean_data)

In [37]:
# list_df

In [38]:
tmp_template = pd.concat(list_df)
cp_tmp_template = tmp_template.copy()
cp_tmp_template

,Votre référence / Your reference,EAN (Cdiscount)\nGTIN (Octopia),Stock,Prix de référence (TTC) / Reference price (incl.tax),Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales,Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days),Suivi / Tracked (Mandatory),ecommandé / Registered
0,ms-8806094561838,8806094561838,10,636.80400,530.6700,3,0.00,0.00
1,ms-8806090892127,8806090892127,10,574.56000,478.8000,3,5.00,5.00
2,ms-8806090882531,8806090882531,10,764.46804,637.0567,3,0.00,0.00
3,ms-8806090892875,8806090892875,10,593.69604,494.7467,3,35.00,35.00
4,ms-8806090891915,8806090891915,10,622.44000,518.7000,3,0.00,0.00
...,...,...,...,...,...,...,...,...
445,ms-4054278786384,4054278786384,10,606.46404,505.3867,3,8.90,8.90
446,ms-4054278605166,4054278605166,10,213.67248,178.0604,3,4.99,4.99
447,ms-4054278505510,4054278505510,10,311.20404,259.3367,3,0.00,0.00
448,ms-3165140746601,3165140746601,10,199.48404,166.2367,3,0.00,0.00
449,ms-4054278618159,4054278618159,10,414.94404,345.7867,3,0.00,0.00

In [39]:
ean_new = tmp_template["EAN (Cdiscount)\nGTIN (Octopia)"].values

In [40]:
ean_already_crawled = pd.read_excel("s26_v4.xlsx", header=None).loc[4:, 1].values

In [41]:
count = 0
cp_tmp_template = tmp_template.copy()
for ean in ean_already_crawled:
    if ean in ean_new:
        count += 1
        # display(
        #     cp_tmp_template.loc[
        #         cp_tmp_template["EAN (Cdiscount)\nGTIN (Octopia)"] == ean
        #     ]
        # )
        cp_tmp_template.drop(
            cp_tmp_template.loc[
                cp_tmp_template["EAN (Cdiscount)\nGTIN (Octopia)"] == ean
            ].index,
            inplace=True,
        )

In [42]:
round_tmp_template = cp_tmp_template.round(2)

In [43]:
round_tmp_template

,Votre référence / Your reference,EAN (Cdiscount)\nGTIN (Octopia),Stock,Prix de référence (TTC) / Reference price (incl.tax),Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales,Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days),Suivi / Tracked (Mandatory),ecommandé / Registered
1,ms-8806090892127,8806090892127,10,574.56,478.80,3,5.0,5.0
2,ms-8806090882531,8806090882531,10,764.47,637.06,3,0.0,0.0
4,ms-8806090891915,8806090891915,10,622.44,518.70,3,0.0,0.0
5,ms-8806092522770,8806092522770,10,406.98,339.15,3,0.0,0.0
6,ms-0711719423898,711719423898,10,758.08,631.74,3,6.0,6.0
...,...,...,...,...,...,...,...,...
443,ms-4046664085614,4046664085614,10,638.34,531.95,3,49.9,49.9
445,ms-4054278786384,4054278786384,10,606.46,505.39,3,8.9,8.9
447,ms-4054278505510,4054278505510,10,311.20,259.34,3,0.0,0.0
448,ms-3165140746601,3165140746601,10,199.48,166.24,3,0.0,0.0
449,ms-4054278618159,4054278618159,10,414.94,345.79,3,0.0,0.0

In [56]:
crawl_ = pd.read_excel(
    "/home/user/Téléchargements/partial_template-2023-07-09.xlsx", index_col=0
)
crawl_

,Votre référence / Your reference,EAN (Cdiscount)\nGTIN (Octopia),Stock,Prix de référence (TTC) / Reference price (incl.tax),Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales,Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days),Suivi / Tracked (Mandatory),ecommandé / Registered
0,ms-0711719423898,711719423898,10,631.74,758.08,5,6.00,6.00
1,ms-0711719449799,711719449799,10,731.49,877.78,5,0.00,0.00
2,ms-0045496453596,45496453596,10,359.09,430.90,5,6.00,6.00
3,ms-0711719424994,711719424994,10,768.58,922.30,5,6.00,6.00
4,ms-0045496453435,45496453435,10,425.59,510.70,5,3.49,3.49
...,...,...,...,...,...,...,...,...
474,ms-4053035580104,4053035580104,10,76.86,92.23,5,0.00,0.00
475,ms-4053035242002,4053035242002,10,43.76,52.51,5,6.95,6.95
476,ms-4053035206677,4053035206677,10,53.07,63.68,5,6.95,6.95
477,ms-4053035255002,4053035255002,10,50.47,60.57,5,0.00,0.00
478,ms-4053035101194,4053035101194,10,35.90,43.08,5,5.90,5.90

In [60]:
pd.concat([crawl_, round_tmp_template], axis=1)
mask = round_tmp_template["EAN (Cdiscount)\nGTIN (Octopia)"].isin(
    crawl_["EAN (Cdiscount)\nGTIN (Octopia)"]
)

211

In [69]:
to_add = round_tmp_template[~mask]
pd.concat([to_add, crawl_], axis=0)

,Votre référence / Your reference,EAN (Cdiscount)\nGTIN (Octopia),Stock,Prix de référence (TTC) / Reference price (incl.tax),Prix de référence (€) (TTC) - Applicable uniquement pour les soldes /\nReference Price (€)(incl.tax) - Applicable only for Sales,Délai de préparation\n(nb jours ouvrés max) / Preparation Time\n(Max working days),Suivi / Tracked (Mandatory),ecommandé / Registered
19,ms-8806092947719,8806092947719,10,263.32,219.44,3,6.00,6.00
26,ms-0889842651393,889842651393,10,478.78,398.99,3,0.00,0.00
28,ms-0711719827399,711719827399,10,153.18,127.65,3,0.00,0.00
37,ms-0197192992593,197192992593,10,766.06,638.39,3,11.90,11.90
62,ms-3221616000438,3221616000438,10,207.46,172.89,3,0.00,0.00
...,...,...,...,...,...,...,...,...
474,ms-4053035580104,4053035580104,10,76.86,92.23,5,0.00,0.00
475,ms-4053035242002,4053035242002,10,43.76,52.51,5,6.95,6.95
476,ms-4053035206677,4053035206677,10,53.07,63.68,5,6.95,6.95
477,ms-4053035255002,4053035255002,10,50.47,60.57,5,0.00,0.00
478,ms-4053035101194,4053035101194,10,35.90,43.08,5,5.90,5.90

In [139]:
round_tmp_template.to_excel(
    f"/home/user/Documents/Data_crawl/partial_template-{time.strftime('%Y-%m-%d')}.xlsx",
    sheet_name="Fichier Intégration Offre",
)

In [202]:
# tmp_template["EAN (Cdiscount)\nGTIN (Octopia)"].apply(lambda x: len(str(x)))